# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pretty_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(693, 398)
        font = QtGui.QFont()
        font.setPointSize(7)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background: #a7d4ff")
        self.previous_button = QtWidgets.QPushButton(Dialog)
        self.previous_button.setGeometry(QtCore.QRect(40, 40, 221, 61))
        self.previous_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previous_button.setStyleSheet("  text-align: center;\n"
"  background: #5468ff;\n"
"  border-radius: 15px;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"font-size: 26px;")
        self.previous_button.setObjectName("previous_button")
        self.next_button = QtWidgets.QPushButton(Dialog)
        self.next_button.setGeometry(QtCore.QRect(430, 40, 221, 61))
        self.next_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button.setStyleSheet("  text-align: center;\n"
"  background: #5468ff;\n"
"  border-radius: 15px;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"font-size: 26px;")
        self.next_button.setObjectName("next_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 170, 591, 111))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("  background: #7282ff;\n"
"text-align: center;\n"
"color: #fff;\n"
"font-size: 30px;\n"
"padding: 20px;\n"
"text-align: center;\n"
"border-radius: 15px")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pages = QtWidgets.QLabel(Dialog)
        self.pages.setGeometry(QtCore.QRect(570, 330, 101, 41))
        self.pages.setStyleSheet("\n"
"  background: #5468ff;\n"
"  border-radius: 8px;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"font-size: 16px;\n"
"padding-left: 10px")
        self.pages.setObjectName("pages")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.previous_button.setText(_translate("Dialog", "Previous"))
        self.next_button.setText(_translate("Dialog", "Next"))
        self.pages.setText(_translate("Dialog", "Page: 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
